// ===== mirAI Curriculum - Master Data =====
// Industries, subjects, school levels, sample curricula, rubrics, etc.

window.MIRAI_DATA = {
  // ===== 業界カテゴリ =====
  industries: [
    {
      id: 'manufacturing',
      name: '製造業',
      tagline: 'ものづくり × デジタル技術',
      desc: 'スマートファクトリーとIoTで「ものづくり」の未来を創造する。',
      icon: '🏭',
      color: 'from-blue-500 to-blue-700',
      colorHex: '#3b82f6',
      image: 'https://images.unsplash.com/photo-1565514020179-026b92b84bb6?w=800&q=80',
      tags: ['生産技術エンジニア', '品質管理スペシャリスト'],
      themes: ['IoTセンサー', 'ロボティクス', 'デジタルツイン', '品質管理AI'],
    },
    {
      id: 'construction',
      name: '建設・都市',
      tagline: '空間デザイン × テクノロジー',
      desc: 'BIM・スマートシティで未来の街づくりを設計する。',
      icon: '🏗️',
      color: 'from-orange-500 to-amber-700',
      colorHex: '#f97316',
      image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80',
      tags: ['建築士', '都市プランナー'],
      themes: ['BIM/CIM', 'スマートシティ', '建築シミュレーション', '都市計画'],
    },
    {
      id: 'retail',
      name: '小売・UX',
      tagline: '顧客体験 × データ分析',
      desc: '新しい購買体験を設計し、データドリブンな小売を実現する。',
      icon: '🛍️',
      color: 'from-pink-500 to-rose-600',
      colorHex: '#ec4899',
      image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80',
      tags: ['マーケター', 'UXデザイナー'],
      themes: ['顧客分析', 'オムニチャネル', 'UXデザイン', 'パーソナライズ'],
    },
    {
      id: 'finance',
      name: '金融・FinTech',
      tagline: 'FinTech × データサイエンス',
      desc: '金融の未来をデータと数理で探究する。',
      icon: '💰',
      color: 'from-yellow-500 to-amber-600',
      colorHex: '#eab308',
      image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80',
      tags: ['金融アナリスト', 'FinTechエンジニア'],
      themes: ['ブロックチェーン', '統計分析', 'リスク管理', 'アルゴリズム取引'],
    },
    {
      id: 'healthcare',
      name: '医療・ヘルスケア',
      tagline: '医療 × ICT',
      desc: '人々の健康を支える医療情報システムを設計する。',
      icon: '🏥',
      color: 'from-red-500 to-rose-600',
      colorHex: '#ef4444',
      image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&q=80',
      tags: ['医療情報技師', 'ヘルスケアデザイナー'],
      themes: ['電子カルテ', '医療AI', 'バイオインフォマティクス', '遠隔医療'],
    },
    {
      id: 'media',
      name: 'コンテンツ・配信',
      tagline: 'コンテンツ制作 × デジタル配信',
      desc: '新しい表現と配信の形をクリエイティブに探究する。',
      icon: '🎬',
      color: 'from-purple-500 to-fuchsia-600',
      colorHex: '#a855f7',
      image: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&q=80',
      tags: ['コンテンツクリエイター', 'プロデューサー'],
      themes: ['映像制作', 'ストリーミング', 'XR', 'クリエイティブAI'],
    },
    {
      id: 'logistics',
      name: '物流・SCM',
      tagline: 'ロジスティクス × 最適化',
      desc: '効率的な配送と供給網をデータで最適化する。',
      icon: '🚚',
      color: 'from-teal-500 to-cyan-700',
      colorHex: '#14b8a6',
      image: 'https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&q=80',
      tags: ['ロジスティクスエンジニア', 'SCMスペシャリスト'],
      themes: ['ルート最適化', '倉庫自動化', 'SCM', 'ドローン配送'],
    },
    {
      id: 'agriculture',
      name: '農業・食品',
      tagline: 'アグリテック × データ',
      desc: '持続可能な食の未来をテクノロジーで実現する。',
      icon: '🌾',
      color: 'from-green-500 to-emerald-700',
      colorHex: '#22c55e',
      image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800&q=80',
      tags: ['アグリエンジニア', '食品開発スペシャリスト'],
      themes: ['スマート農業', '植物工場', '食品テック', 'サプライチェーン'],
    },
    {
      id: 'environment',
      name: '気象・環境',
      tagline: '気象データ × DX',
      desc: '防災と環境課題にデータサイエンスで挑む。',
      icon: '🌦️',
      color: 'from-sky-500 to-blue-700',
      colorHex: '#0ea5e9',
      image: 'https://images.unsplash.com/photo-1561553873-e8491a564fd0?w=800&q=80',
      tags: ['気象予報士', 'データサイエンティスト'],
      themes: ['気象予測', '防災システム', '環境モニタリング', '再生可能エネルギー'],
    },
    {
      id: 'custom',
      name: 'カスタム業種',
      tagline: '独自業界 × オリジナル設計',
      desc: '独自の業界・事業内容に合わせて自由にカリキュラムを設計。',
      icon: '✏️',
      color: 'from-slate-500 to-slate-700',
      colorHex: '#64748b',
      image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80',
      tags: ['自由設定'],
      themes: ['カスタム'],
    },
  ],

  // ===== 対象学校段階 =====
  schoolLevels: [
    { id: 'junior_high', name: '中学校', grades: [1, 2, 3], color: 'sky' },
    { id: 'high', name: '高等学校', grades: [1, 2, 3], color: 'blue' },
    { id: 'kosen', name: '高等専門学校', grades: [1, 2, 3, 4, 5], color: 'indigo' },
    { id: 'university', name: '大学', grades: [1, 2, 3, 4], color: 'purple' },
  ],

  // ===== 教科 =====
  subjects: [
    { id: 'info_2', name: '情報Ⅱ', schoolLevels: ['high'], color: '#3366ff' },
    { id: 'info_1', name: '情報Ⅰ', schoolLevels: ['high'], color: '#3366ff' },
    { id: 'inquiry', name: '探究', schoolLevels: ['junior_high', 'high'], color: '#7c3aed' },
    { id: 'math', name: '数学', schoolLevels: ['junior_high', 'high', 'kosen', 'university'], color: '#10b981' },
    { id: 'physics', name: '物理', schoolLevels: ['high', 'kosen', 'university'], color: '#f59e0b' },
    { id: 'biology', name: '生物', schoolLevels: ['high', 'kosen', 'university'], color: '#22c55e' },
    { id: 'chemistry', name: '化学', schoolLevels: ['high', 'kosen', 'university'], color: '#ef4444' },
    { id: 'social', name: '社会', schoolLevels: ['junior_high', 'high'], color: '#ec4899' },
    { id: 'tech', name: '技術', schoolLevels: ['junior_high'], color: '#6366f1' },
    { id: 'career', name: 'キャリア教育', schoolLevels: ['junior_high', 'high', 'kosen', 'university'], color: '#06b6d4' },
  ],

  // ===== 学習指導要領のサンプル（簡略化） =====
  curriculumGuidelines: {
    info_2: {
      subject: '情報Ⅱ',
      pillars: [
        { id: 'p1', name: '情報社会と問題解決', keywords: ['データ活用', '情報倫理', 'デジタル化'] },
        { id: 'p2', name: 'コミュニケーションと情報デザイン', keywords: ['情報デザイン', 'ユニバーサルデザイン', '可視化'] },
        { id: 'p3', name: 'コンピュータとプログラミング', keywords: ['アルゴリズム', 'プログラミング', 'モデル化'] },
        { id: 'p4', name: '情報通信ネットワークとデータの活用', keywords: ['ネットワーク', 'データベース', '統計', 'AI'] },
      ],
    },
    inquiry: {
      subject: '探究',
      pillars: [
        { id: 'q1', name: '課題の設定', keywords: ['社会課題', '問いの設計', '仮説'] },
        { id: 'q2', name: '情報の収集', keywords: ['調査', 'インタビュー', '一次情報'] },
        { id: 'q3', name: '整理・分析', keywords: ['データ分析', '可視化', '考察'] },
        { id: 'q4', name: 'まとめ・表現', keywords: ['プレゼン', '対話', '発信'] },
      ],
    },
    math: {
      subject: '数学',
      pillars: [
        { id: 'm1', name: '数と式', keywords: ['代数', '方程式', '関数'] },
        { id: 'm2', name: '統計', keywords: ['データの分析', '確率', '推測統計'] },
        { id: 'm3', name: '図形・空間', keywords: ['幾何', 'ベクトル', '空間認識'] },
      ],
    },
    physics: {
      subject: '物理',
      pillars: [
        { id: 'ph1', name: '力学', keywords: ['運動', 'エネルギー', '力'] },
        { id: 'ph2', name: '電磁気', keywords: ['電気回路', '磁気', '電磁誘導'] },
        { id: 'ph3', name: '波動・光', keywords: ['波', '光', '音'] },
      ],
    },
  },

  // ===== ルーブリック評価テンプレート =====
  rubricTemplate: {
    criteria: [
      { id: 'c1', name: '知識・理解', description: '学習内容の正確な理解度' },
      { id: 'c2', name: '思考・判断', description: '課題に対する思考の深さ' },
      { id: 'c3', name: '表現・発信', description: 'アイデアの伝達力' },
      { id: 'c4', name: '主体性・協働', description: '取り組み姿勢と協働性' },
    ],
    levels: [
      { id: 'l1', name: 'A: 大変良い', value: 4 },
      { id: 'l2', name: 'B: 良い', value: 3 },
      { id: 'l3', name: 'C: 標準', value: 2 },
      { id: 'l4', name: 'D: 要努力', value: 1 },
    ],
  },

  // ===== サンプルカリキュラム（デモ用、ライブラリにプリロード） =====
  sampleCurricula: [
    {
      id: 'curr-001',
      title: 'スマートファクトリー入門 - IoTで変わる「ものづくり」',
      industry: 'manufacturing',
      company: '株式会社サンプル製造',
      subject: 'info_2',
      schoolLevel: 'high',
      grade: 2,
      sessions: 4,
      theme: 'IoTセンサーとデータ活用で工場の生産性を最大化する仕組みを学ぶ',
      tags: ['IoT', 'データ活用', 'AI', 'DX'],
      thumbnail: 'https://images.unsplash.com/photo-1565514020179-026b92b84bb6?w=600&q=80',
      compliance: 92,
      isPublic: true,
      createdAt: '2025-12-10',
      stats: { views: 234, downloads: 87, likes: 45 },
      slides: [
        { title: 'スマートファクトリー入門', subtitle: 'IoTで変わる「ものづくり」', type: 'title', image: 'https://images.unsplash.com/photo-1565514020179-026b92b84bb6?w=800&q=80' },
        { title: '本日のゴール', type: 'objectives', items: ['IoTの仕組みを理解する', 'データの活用方法を学ぶ', '工場の課題と解決策を考える', '自分なりの提案を作る'] },
        { title: 'IoTとは何か？', type: 'content', body: 'Internet of Thingsの略。あらゆる「モノ」をインターネットに接続し、データを収集・活用する技術。', image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80' },
        { title: '工場のセンサーが集めるデータ', type: 'list', items: ['温度・湿度', '振動・音響', '機械の稼働状況', '製品の品質情報', '作業者の動線'] },
        { title: 'ディスカッション', type: 'question', body: 'あなたの学校・身の回りで「IoT化」したらもっと便利になるものは？グループで5分間ブレストしてみよう。' },
        { title: 'まとめ', type: 'summary', items: ['IoTでものづくりは劇的に変わる', 'データから新しい価値が生まれる', '次回はAIの活用について学ぶ'] },
      ],
    },
    {
      id: 'curr-002',
      title: 'アグリテックで食を守る - データ農業の最前線',
      industry: 'agriculture',
      company: 'グリーンテック株式会社',
      subject: 'inquiry',
      schoolLevel: 'high',
      grade: 1,
      sessions: 6,
      theme: 'データとAIで食料生産をいかに最適化するかを探究する',
      tags: ['アグリテック', 'SDGs', '探究', '持続可能性'],
      thumbnail: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&q=80',
      compliance: 88,
      isPublic: true,
      createdAt: '2025-11-22',
      stats: { views: 312, downloads: 120, likes: 67 },
      slides: [
        { title: 'アグリテックで食を守る', subtitle: 'データで変わる農業の未来', type: 'title', image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800&q=80' },
        { title: '世界の食料問題', type: 'content', body: '2050年、世界の人口は97億人に。食料需要は60%増。私たちは「食」をどう守るか？', image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80' },
        { title: 'アグリテックとは', type: 'list', items: ['ドローンによる空撮監視', 'AIによる病害虫検知', '植物工場の自動化', 'スマート灌漑システム'] },
        { title: '探究の問い', type: 'question', body: '日本の農業の未来を、テクノロジーでどう変えられる？地域の課題を1つ選んで提案しよう。' },
        { title: 'グループワーク', type: 'content', body: '4-5名のグループで、選んだ地域課題に対するアグリテック提案を組み立てる。' },
        { title: 'まとめ・発表', type: 'summary', items: ['持続可能な食料生産の重要性', 'テクノロジーは課題解決の手段', '私たちにできるアクションを考える'] },
      ],
    },
    {
      id: 'curr-003',
      title: 'FinTechで未来予測 - 統計と確率で世界を読む',
      industry: 'finance',
      company: 'フィンテック・ラボ株式会社',
      subject: 'math',
      schoolLevel: 'high',
      grade: 3,
      sessions: 3,
      theme: '金融データから統計的に未来を予測する手法を学ぶ',
      tags: ['統計', 'FinTech', 'データサイエンス', '数学'],
      thumbnail: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&q=80',
      compliance: 95,
      isPublic: true,
      createdAt: '2025-12-01',
      stats: { views: 189, downloads: 76, likes: 33 },
      slides: [
        { title: 'FinTechで未来予測', subtitle: '統計と確率で世界を読む', type: 'title', image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80' },
        { title: '金融データの世界', type: 'content', body: '株価、為替、暗号資産…毎秒膨大なデータが生まれている。数学はこれらをどう読み解くのか？' },
        { title: '統計の基礎', type: 'list', items: ['平均と分散', '正規分布', '相関と因果', '回帰分析'] },
        { title: '実習: 株価データを分析', type: 'question', body: '与えられた1年間の株価データから、平均と標準偏差を計算し、リスクを評価してみよう。' },
        { title: 'まとめ', type: 'summary', items: ['数学は世界の不確実性を扱う言語', 'データは未来予測のヒント', '次回は機械学習の入口へ'] },
      ],
    },
    {
      id: 'curr-004',
      title: '医療AIで命を支える - データから生まれる新しい医療',
      industry: 'healthcare',
      company: 'メディカルAI研究所',
      subject: 'biology',
      schoolLevel: 'high',
      grade: 2,
      sessions: 5,
      theme: '医療現場でAIがどう活用され、何を可能にしているか',
      tags: ['医療AI', 'バイオ', 'ヘルスケア', '生命倫理'],
      thumbnail: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&q=80',
      compliance: 90,
      isPublic: true,
      createdAt: '2025-11-15',
      stats: { views: 267, downloads: 95, likes: 51 },
      slides: [
        { title: '医療AIで命を支える', subtitle: 'データから生まれる新しい医療', type: 'title', image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&q=80' },
        { title: '医療現場の課題', type: 'content', body: '医師不足、診断の精度、医療費の高騰…AIはどう貢献できるのか。' },
        { title: 'AI画像診断の仕組み', type: 'list', items: ['CT/MRIの画像解析', 'がん検出AI', '網膜疾患の発見', '皮膚科診断補助'] },
        { title: '倫理的な問い', type: 'question', body: 'AIが診断ミスをしたら、責任は誰にある？医師？開発者？AIそのもの？グループで議論しよう。' },
        { title: 'まとめ', type: 'summary', items: ['医療AIは強力な「補助者」', '人間の判断は依然として中心', '倫理・法律の議論も同時に必要'] },
      ],
    },
    {
      id: 'curr-005',
      title: 'スマートシティ設計 - データで都市を再構築する',
      industry: 'construction',
      company: '未来都市デザイン株式会社',
      subject: 'inquiry',
      schoolLevel: 'high',
      grade: 2,
      sessions: 4,
      theme: '都市の課題をデータとデザインで解決する手法を体験する',
      tags: ['スマートシティ', '都市計画', 'SDGs', 'デザイン思考'],
      thumbnail: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&q=80',
      compliance: 87,
      isPublic: true,
      createdAt: '2025-10-30',
      stats: { views: 198, downloads: 82, likes: 40 },
      slides: [
        { title: 'スマートシティ設計', subtitle: 'データで都市を再構築する', type: 'title', image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80' },
        { title: '都市の現代的課題', type: 'list', items: ['交通渋滞', '高齢化', 'エネルギー消費', '災害対策'] },
        { title: 'デザイン思考', type: 'content', body: '共感 → 定義 → 発想 → 試作 → テスト。人間中心で都市を設計する。' },
        { title: 'グループワーク', type: 'question', body: 'あなたの街の課題を1つ選んで、スマートシティ的なアプローチを提案しよう。' },
        { title: 'まとめ', type: 'summary', items: ['都市は人と技術の協創', 'データは未来を見せる窓', '小さな提案から街は変わる'] },
      ],
    },
    {
      id: 'curr-006',
      title: '気象データで防災を考える',
      industry: 'environment',
      company: '気象テック株式会社',
      subject: 'physics',
      schoolLevel: 'junior_high',
      grade: 3,
      sessions: 3,
      theme: '気象データとセンサーから防災システムの仕組みを学ぶ',
      tags: ['気象', '防災', 'IoT', '物理'],
      thumbnail: 'https://images.unsplash.com/photo-1561553873-e8491a564fd0?w=600&q=80',
      compliance: 84,
      isPublic: true,
      createdAt: '2025-12-15',
      stats: { views: 145, downloads: 56, likes: 28 },
      slides: [
        { title: '気象データで防災を考える', type: 'title', image: 'https://images.unsplash.com/photo-1561553873-e8491a564fd0?w=800&q=80' },
        { title: '日本の自然災害', type: 'content', body: '地震、豪雨、台風…毎年起こる災害をデータで予測できないか？' },
        { title: 'センサーの仕組み', type: 'list', items: ['気圧センサー', '雨量計', '地震計', '衛星観測'] },
        { title: '探究', type: 'question', body: '自分の住んでいる地域で、どんなセンサーがあると防災に役立つか考えよう。' },
        { title: 'まとめ', type: 'summary', items: ['データは命を守る', '科学は社会の課題解決に役立つ', '私たちにもできる準備がある'] },
      ],
    },
  ],

  // ===== 評価サンプルデータ（ダッシュボード用） =====
  evaluationData: {
    classes: [
      { id: 'cls-1', name: '2年A組', students: 32, curriculumId: 'curr-001' },
      { id: 'cls-2', name: '2年B組', students: 30, curriculumId: 'curr-001' },
      { id: 'cls-3', name: '1年C組', students: 28, curriculumId: 'curr-002' },
    ],
  },

  // ===== 発行済みID（デモログイン用） =====
  validIds: {
    company: ['COMP-001', 'COMP-002', 'COMP-DEMO', 'COMPANY'],
    teacher: ['TEACH-001', 'TEACH-002', 'TEACH-DEMO', 'TEACHER'],
  },
};
